[DEFAULT]
envs = {'dev'='DEV'}
main_env = 'dev'
fetch_child_rows = 1000

[DEV]
'db_type' = 'sqlite'
'db_path' = 'C:/Work/GitHub/db-autotest/Docs/m_sqlite.db'

[META_DB]
db_path = 'C:/Work/GitHub/db-autotest/Docs/m_sqlite.db'

